# Generated by Django 4.2.20 on 2025-04-15 08:01

from django.db import migrations, models
import main.models.admission


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=main.models.admission.generate_application_id, editable=False, max_length=12, unique=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('grade', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_school', models.CharField(max_length=200)),
                ('school_location', models.CharField(max_length=200)),
                ('last_grade_completed', models.CharField(max_length=50)),
                ('languages_spoken', models.CharField(max_length=200)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_relationship', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('hobbies_interests', models.TextField(blank=True, null=True)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('reason_for_applying', models.TextField()),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='admissions/', validators=[main.models.admission.validate_file_extension])),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='admissions/', validators=[main.models.admission.validate_file_extension])),
                ('last_report_card', models.FileField(blank=True, null=True, upload_to='admissions/', validators=[main.models.admission.validate_file_extension])),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to='admissions/', validators=[main.models.admission.validate_file_extension])),
                ('immunization_records', models.FileField(blank=True, null=True, upload_to='admissions/', validators=[main.models.admission.validate_file_extension])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
